.\" This man page for produttore_e_consumatore2
.TH produttore_e_consumatore2 "1" "2021-03-20" "produttore_e_consumatore2 01.01" "User Commands"
.SH NAME
produttore_e_consumatore2
.SH SYNOPSIS
.B produttore_e_consumatore2 - get virtal machines infos
.br
.B produttore_e_consumatore2 [--batch | -b] - disable GUI mode
.br
.B produttore_e_consumatore2 [--verbose] - verbose mode (if not in GUI mode)
.br
.B produttore_e_consumatore2 [--csv] - enable csv output (if not in GUI mode)
.br
.B produttore_e_consumatore2 [--url=... --token=... --OStable=... --NETtable=...] - enable the upload to HarperDB (Replace "..." with the value(s)) (if not in GUI mode)
.br
.SH DESCRIPTION
Multiprocessing
.SH AUTHORS
Castellani Davide: owner